export const $minutos = document.querySelector(".minutero");
export const $input = document.getElementById("input");
export const $enviar1 = document.getElementById("enviar");
export const $perrafo = document.querySelector(".parrafo");
export const $iniciar = document.querySelector(".botoninicio");
export const $detener = document.querySelector(".botondetener");
export const $tarea = document.querySelector(".tareacontador");
export const $minuto = document.querySelector(".minutos");
export const $segundo= document.querySelector(".segundos");
